---
##############################
# Configuration for Bot #
# Add bots to your MCPE server #
##############################

# Make the bots sneak
sneak: true
# Make the bots un-sneak
unsneak: true
# Make the bots rotate
rotation: true
rotate-distance: 5
# Make the bots swing
swing: true
# Make the bots walk
walk: true
walk-distance: 0.5
# Add circle particles to your bots
particles: true
# damage mode for bots
damage: false

# Only support 1 level for now
level: world
...
