---
# AutoClearLagg (ACL) Settings

# Seconds between each clear lagg
seconds: 600

# Things to clear
items: true
mobs: true

# Messages broadcasted
time-left-message: 
items-cleared-message: 
mobs-cleared-message: 

# Countdown times
times: [60, 30, 15, 10, 5, 4, 3, 2, 1]
...
