---
version: 1.4.10-6
default-factions-plugin: FactionsPro
enable-multiworld-chat: false
groups:
  Guest:
    chat: §d[§eCư Dân§d] §b{display_name} &d> &f{msg}
    nametag: §d[§eCư Dân§d] §b{display_name} §d>§f {msg}
    worlds: []
  DNP30:
    chat: §d[§eCư Dân§d] §b{display_name} &d> &7{msg}
    nametag: '§d[§eCư Dân§d] §b{display_name}§c§l Điểm Nhân Phẩm: 30 §d> §f{msg}'
    worlds: []
  DNP10:
    chat: §7Có vẻ như {display_name} §r§7muốn nói gì đó!
    nametag: '§d[§eCư Dân§d] §b{display_name}§c§l Điểm Nhân Phẩm: 10'
    worlds: []
  Admin:
    chat: '&c[Admin] &7{fac_rank}{fac_name}&6 {display_name} &d>&b {msg}'
    nametag: '&a[Admin]&e {fac_rank}{fac_name} &6{display_name}'
    worlds: []
  Owner:
    chat: '&d[Owner] &c{fac_rank}{fac_name} &b{display_name} &c>&6> &b{msg}'
    nametag: '&d[Owner]&c {fac_rank}{fac_name} &b{display_name}'
    worlds: []
  OP:
    chat: '&a[OP] &5{fac_rank}{fac_name}&b {prefix}{display_name}{suffix} &c>&6> &f{msg}'
    nametag: '&a[OP] &c{fac_rank}{fac_name} &b{display_name}'
    worlds: []
  Đĩ:
    nametag: §d[§eCư Dân§d] §d[§eQUEEN§d]§b {display_name} §c(§eBóng Chúa§c) §d>§e
      {msg}
    chat: §d[§eCư Dân§d] §d[§eQUEEN§d]§b {display_name}§e > §e{msg}
  Gay:
    nametag: '&8&l[Gay]&f&r {display_name}'
    chat: '&8&l[Gay]&f&r {display_name} &7> {msg}'
...
